---
title: "Browse data"
output: html_document
---


##### Source

Pubmed ID of publication or other ID. Most sources have PMID.

##### Contributor

Citation including primary author and publication year.

##### Variable

Short data variable name.

##### Description

Description of data variable.

##### OBITerm

The applicable methods used to generate the data. The terms are from the Ontology of Biomedical Investigations (OBI).

##### IndividualLevelData

Denotes whether data is available at donor-level. In some experiments, data were generated by pooling samples.

##### InApp

Denotes whether data is available in the application. Some data have not been shared or made public by the authors.

##### DataSource

A reference figure/table that contains some or all of the data.

##### DataSourceLink

External link to DataSource. Typically points to the original data in a supplemental file or to an external database where data has been deposited. The original sources can provide more detail about methodology, definitions and other metadata, but are in a variety of formats not universally machine-readable (e.g. PDF, Excel).
