#' Experimental nPOD data curated from over 70 publications
#' 
#' A dataset of nPOD cases by variable. This is used by \code{\link{matrixCtrl}}.
#' 
#' @format A data.table with 460 rows and 218 columns
"cdata"

#' Correlation data
#' 
#' A dataset generated by \code{\link{data2cor}} with \code{cdata} as input.
#' This is used by \code{\link{matrixCtrl}}.
#' 
#' @format A list containing a matrix M, correlations in \code{cdata}, and matrix N.
"cordata"

#' Metadata for \code{cdata}
#' 
#' Contains a table of variables annotated with several types of metadata. 
#' This \code{metadata} data object is used by \code{\link{matrixCtrl}}
#' 
#' @format A data.table with 460 rows and 218 columns
"metadata"

#' Data for npodgraph
#' 
#' This is used by \code{\link{cohortGraph}}
#' 
#' @format A data.table
"ndata"

#' Pre-built visNetwork graph
#' 
#' This is used by \code{\link{cohortGraph}}
#' 
#' @format visNetwork graph
"npodgraph"

#' A limited nPOD dataset containing variables used for matching
#' 
#' This is used by \code{\link{refSubset}}
#' 
#' @format A data.table with 449 rows and 23 columns
"npodX"